<?php


namespace App\Exceptions;


use Illuminate\Contracts\Container\Container;
use Illuminate\Contracts\Debug\ExceptionHandler as ExceptionHandlerContract;
use NunoMaduro\Collision\Adapters\Laravel\ExceptionHandler;
use Throwable;

class UnauthorizedActionException extends ExceptionHandler
{
/*    public function __construct(Container $container, ExceptionHandlerContract $appExceptionHandler)
    {
        parent::__construct($container, $appExceptionHandler);
    }*/

    public function render($request, Throwable $e)
    {
        return response()->view('401');
        //return parent::render($request, $e); // TODO: Change the autogenerated stub
    }
}
